- setup
- collection of
- surrounded by
- with attached
- attached upper shelving unit
- with mirror
- mirror on top
- with shelving unit
- including
- two stacked
- six chairs
- multiple shelves holding
- bathroom vanity
- dining setup
