bed.n.01: bed
double_bed.n.01: bed
bunk_bed.n.01: bunk_bed
nightstand.n.01: nightstand
desk.n.01: desk
writing_desk.n.01: desk
dining_table.n.01: dining_table
coffee_table.n.01: coffee_table
end_table.n.01: side_table
console_table.n.01: console_table
table.n.02: table
chair.n.01: chair
swivel_chair.n.01: office_chair
armchair.n.01: armchair
club_chair.n.01: armchair
easy_chair.n.01: armchair
sofa.n.01: sofa
stool.n.01: stool
ottoman.n.03: ottoman
bench.n.01: bench
chest_of_drawers.n.01: dresser
wardrobe.n.01: wardrobe
bookcase.n.01: bookcase
bookshelf.n.01: bookcase
cabinet.n.01: cabinet
kitchen_cabinet.n.02: cabinet
rug.n.01: rug
wall_art.n.01: wall_art
wall_sign.n.01: wall_art
wall_mirror.n.01: wall_mirror
vase.n.01: vase
flower_in_vase.n.01: flower_in_vase
potted_plant.n.01: plant
throw_pillow.n.01: throw_pillow
floor_lamp.n.01: floor_lamp
table_lamp.n.01: table_lamp
wall_lamp.n.01: wall_lamp
pendant_lamp.n.01: ceiling_lamp
ceiling_lamp.n.01: ceiling_lamp
chandelier.n.01: ceiling_lamp
ceiling_fan.n.01: ceiling_fan
refrigerator.n.01: refrigerator
oven.n.01: oven
"washer.n.03,dryer.n.01": washer_dryer
sink.n.01: sink
toilet.n.02: toilet
showerhead.n.01: shower_fixture
